name: fish_fusion
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - pytorch
  - conda-forge
dependencies:
  - ca-certificates=2023.08.22=haa95532_0
  - libffi=3.4.4=hd77b12b_0
  - openssl=3.0.12=h2bbff1b_0
  - pip=23.3=py38haa95532_0
  - python=3.8.18=h1aa4202_0
  - setuptools=68.0.0=py38haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.41.2=py38haa95532_0
  - pip:
    - antlr4-python3-runtime==4.9.3
    - asttokens==2.4.1
    - audioread==3.0.1
    - backcall==0.2.0
    - certifi==2023.11.17
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - colorama==0.4.6
    - contourpy==1.1.1
    - cycler==0.12.1
    - decorator==5.1.1
    - executing==2.0.1
    - filelock==3.13.1
    - fonttools==4.45.0
    - fsspec==2023.10.0
    - idna==3.4
    - importlib-metadata==6.8.0
    - importlib-resources==6.1.1
    - ipdb==0.13.13
    - ipython==8.12.3
    - jedi==0.19.1
    - jinja2==3.1.2
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - lazy-loader==0.3
    - librosa==0.10.1
    - llvmlite==0.41.1
    - markupsafe==2.1.3
    - matplotlib==3.7.4
    - matplotlib-inline==0.1.6
    - mpmath==1.3.0
    - msgpack==1.0.7
    - networkx==3.1
    - numba==0.58.1
    - numpy==1.24.4
    - omegaconf==2.3.0
    - opencv-python==4.8.1.78
    - packaging==23.2
    - parso==0.8.3
    - pickleshare==0.7.5
    - pillow==10.1.0
    - platformdirs==4.0.0
    - pooch==1.8.0
    - prompt-toolkit==3.0.41
    - pure-eval==0.2.2
    - pycparser==2.21
    - pygments==2.17.2
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - pyyaml==6.0.1
    - requests==2.31.0
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - six==1.16.0
    - soundfile==0.12.1
    - soxr==0.3.7
    - stack-data==0.6.3
    - sympy==1.12
    - threadpoolctl==3.2.0
    - tomli==2.0.1
    - torch==2.1.1
    - torchvision==0.16.1
    - tqdm==4.66.1
    - traitlets==5.13.0
    - typing-extensions==4.8.0
    - urllib3==2.1.0
    - wcwidth==0.2.12
    - zipp==3.17.0
# prefix: H:\anaconda3\envs\fish_fusion
prefix: D:\Anaconda\envs\fish_fusion

