Exp_name: audio-video-fusion

Modality: 'audio_video'

Training:
    Batch_size: 8
    Max_epoch: 200
    learning_rate: 1e-3
    seed: 25
    classes_num: 4

Audio_features:
    # sample_rate: 64000
    sample_rate: 64000
    window_size: 512
    hop_size: 256
    mel_bins: 64
    fmin: 1
    fmax: 128000

Model:
    video_name: S3D
    audio_name: Cnn6

Workspace: 'Fish_workspace'

